server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:~/kashite;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update

#mvc:
#  static-path-pattern=/**:

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      name:
        mode: subscribing
        source: eventBus